### ISSUE TITLE
Consumers

### ISSUE THREAD

**Issue by kodeine** [benMain/nest-kinesis-producer#12]
Hello 
I am new to kinesis, do we need a consumer as well? If so do you plan on supporting that in this lib?

I am thinking between Kafka or Kinesis, nestjs supports Kafka in microservices but not kinesis.

**Comment by benMain** [comment]
@kodeine That's an interesting idea.  The MicroServices approach would be interesting. We primarily use this inside of Lambda Functions that receive their events from a KinesisEventSource.

**Comment by benMain** [comment]
I'm going to close this as a consumer is isolated functionality.
